name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    name: Release
    strategy:
      matrix:
        kind: ['linux', 'windows', 'macOS']
        include:
          - kind: linux
            os: ubuntu-latest
            target: linux-x64
          - kind: windows
            os: windows-latest
            target: win-x64
          - kind: macOS
            os: macos-latest
            target: osx-x64
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    #- name: Generate release tag
    #  id: tag
    #  run: |
    #    echo "::set-output name=release_tag::UserBuild_$(date +"%Y.%m.%d_%H-%M")"
    - name: Publish framework dependent
      shell: bash
      run: |
        release_name="PolParser-alpha-${{ matrix.target }}"
        # Build no self contained
        dotnet publish src/PolParser/PolParser.csproj --framework net6.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name" --no-self-contained
        
        # Pack files
        if [ "${{ matrix.target }}" == "win-x64" ]; then
          # Pack to zip for Windows
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
        else
          tar czvf "${release_name}.tar.gz" "$release_name"
        fi
        
        # Delete output directory
        rm -r "$release_name"
    - name: Publish framework independent
      shell: bash
      run: |
        release_name="PolParser-alpha-${{ matrix.target }}-self-contained"
        # Build self contained & trimmed
        dotnet publish src/PolParser/PolParser.csproj --framework net6.0 --runtime "${{ matrix.target }}" -c Release -o "$release_name" --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true 
        
        # Remove PDB files
        rm ./${release_name}/*.pdb
        # Pack files
        if [ "${{ matrix.target }}" == "win-x64" ]; then
          # Pack to zip for Windows
          7z a -tzip "${release_name}.zip" "./${release_name}/*"
        else
          tar czvf "${release_name}.tar.gz" "$release_name"
        fi
        
        # Delete output directory
        rm -r "$release_name"
        
    - name: Enumerate root folder
      shell: bash
      run: ls

    - name: Enumerate folder structure
      shell: bash
      run: ls -R

    - name: GH Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        #tag_name: ${{ steps.tag.outputs.release_tag }}
        tag_name: "alpha"
        files: |
          *.zip
          *.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
